### PR TITLE
Fixed Repository

### PR DESCRIPTION
**Pull request by vicajilau**
- This solves [the following issue](https://github.com/TerminalStudio/dartssh2/issues/105) caused in the new Flutter 3.24 version. 
- Development dependencies has been updated to the latest versions. 
- Regular Dependencies has been updated to the latest versions.

### CODE REVIEW

**Comment by acastanos** [comment]
Just what I was looking for, looking forward to seeing this solution merge into the main branch. @xtyxtyx Could you check this PR, thank you very much

**Comment by 13thdeus** [comment]
I need this one too

**Comment by payam-zahedi** [comment]
Can you please take a look at this one @xtyxtyx 

We all need this

**Comment by vicajilau** [comment]
Due to the inactivity of this repository and the need to maintain it within one of the Google Summer of Code organizations in which I collaborate. If anyone else needs it, [this is the new repository](https://github.com/vicajilau/dartssh4) created from this one with this change (and others applied).

**Pull request merged**
